# Generated by Django 3.1.5 on 2021-01-25 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosteldetail',
            name='type',
            field=models.CharField(choices=[('None', 'None'), ('Boys', 'Girls')], default='None', max_length=1000),
        ),
    ]
