# Generated by Django 3.1.5 on 2021-01-25 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0002_hosteldetail_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosteldetail',
            name='type',
            field=models.CharField(choices=[('None', 'None'), ('Boys', 'Boys'), ('Girls', 'Girls')], default='None', max_length=1000),
        ),
    ]
